version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: docker-hub
          environment:
            - DOCKERHUB_REPO: sasnouskikh
          command: sh -c "*/*/build.sh"
