version: 2
jobs:
  build:
    docker:
    - image: docker:18.06
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker-hub
          environment:
            - DOCKERHUB_REPO: sasnouskikh
          command: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD && for script in $(find ./ -name build.sh); do $script; done
