version: 2
jobs:
  build:
    docker:
    - image: docker:18:06
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: docker-hub
          environment:
            - DOCKERHUB_REPO: sasnouskikh
          command: sh -c "*/*/build.sh"
